# Generated by Django 4.0 on 2021-12-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(blank=True, default='', max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
